// ***************** Player actions
export const UPDATE_PLAYER_POSITION = "UPDATE_PLAYER_POSITION";
export const UPDATE_PLAYER_INVULNERABLE = "UPDATE_PLAYER_INVULNERABLE";

export const UPDATE_USER_INFO = "UPDATE_USER_INFO";